$ANSIBLE_VAULT;1.1;AES256
36303362636132393031636166323734613065643762643164616530666638366537373731333939
3162306539383461306133323132623166373637633666360a323534393730353932633438636162
30373036333935343437643130626339363936323631316332363832646638323365633065623435
3861343461346161340a383830343739653633633237383763613663363564393562626264353566
35363035396664313365363366666261333466353538613138393334666565363865383965643436
32633864313737366631386337633331306631376334386366376365313532313464326131663563
38653461343864306137313561386630383466643439623138343661663534666264666130653964
30623938666537393538626438663933356166636134663237376139656366376137613665663661
32646134653939373763643063383131636262356138663162656136653265666663663562333132
66333934356530633262646231636338376236326162356463656661393431343539313031313463
66623831393062313738623535303132383638366631626538653565343736613837376161616335
62613135303133303932313561643537363565316466663533356162616363346635663630626162
63386335333164323131383565303539376562373334613638336535343964646664323933666232
39376630636636306635303231393931323164376562616636643264353561653064663561333035
37303162393937643230373133373638396462356532366131353931353031343239646132633263
32616336363933333166613637323766656366303930343064333437643163663139336534346662
62383231386536343633373033646335386664353134663362663239323732313965333437646538
64366261613334643832326163323761643835623936303461373837623338333837643335303366
66633061363262353734666132356536363865303730303062643833653364356632383032653539
32656136383663613664
