---
controller_credentials:
- name: "Homelab - cnorville"
  description: "Credentials for Homelab Machines"
  organization: Default
  credential_type: Machine
  inputs:
    username: cnorville
    password: "{{ cnorville_password }}"