---
aap_organizations:
  - name: The Rick James Organization
    description: The Rick James Organization - Superfreak
  - name: Norville Enterprises
    description: Norville Development Environment Organization