---
controller_projects:
  - name: Crowdstrike
    organization: Norville Enterprises
    scm_type: git
    scm_url: https://github.com/cnorville90/ansible-crowdstrike.git
    scm_branch: main
    description: Crowdstrike Playbooks